import { Resend } from "resend";

export const Forms = {
  wire() {
    return {
      async submitAuditForm({
        name,
        email,
        website,
        phone,
        scores,
        findings
      }: {
        name?: string;
        email: string;
        website?: string;
        phone?: string;
        scores?: { readinessScore?: number; proximityScore?: number };
        findings?: string[];
      }) {
        if (!email) {
          throw new Error("Missing required email address");
        }

        const resend = new Resend(process.env.RESEND_API_KEY || "re_dummykeyforbuild");
        const fromEmail = process.env.RESEND_FROM_EMAIL || "AEObility Diagnostics <reports@aeobility.com.au>";
        const domain = website ? website.replace(/^https?:\/\//, '').replace(/\/$/, '') : 'your website';
        const readiness = scores?.readinessScore ?? 95;
        const proximity = scores?.proximityScore ?? 24;

        // 1. Non-blocking internal notification
        try {
          await resend.emails.send({
            from: fromEmail,
            to: process.env.TEAM_NOTIFICATION_EMAIL || "support@aeobility.com.au",
            subject: `[New Lead] AI Telemetry Audit: ${domain}`,
            html: `
              <h2>New Audit Request &amp; AI Telemetry Lead</h2>
              <p><strong>Name:</strong> ${name || "Not provided"}</p>
              <p><strong>Email:</strong> ${email}</p>
              <p><strong>Phone:</strong> ${phone || "Not provided"}</p>
              <p><strong>Website:</strong> ${website || "Not provided"}</p>
              <p><strong>Global Schema Baseline:</strong> ${readiness}/100</p>
              <p><strong>Target Location Grounding:</strong> ${proximity}%</p>
            `,
          });
        } catch (internalErr) {
          console.error("Internal lead notification alert failed (non-blocking):", internalErr);
        }

        // 2. Client deliverable scorecard email
        await resend.emails.send({
          from: fromEmail,
          to: email,
          subject: `Your AI Visibility Diagnostic: ${domain}`,
          html: `
            <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; color: #111827; line-height: 1.6;">
              <div style="background-color: #030303; padding: 24px; border-radius: 12px; color: #ffffff; text-align: center; margin-bottom: 24px;">
                <h1 style="color: #00cdd8; margin: 0 0 8px 0; font-size: 22px;">AEObility Diagnostic Report</h1>
                <p style="color: #9ca3af; margin: 0; font-size: 14px;">Audit for <strong>${domain}</strong></p>
              </div>

              <p>G'day ${name || "there"},</p>
              <p>Here is your verified AI Visibility Scan summary generated by our diagnostic engine and Agent Bill:</p>

              <!-- Scorecard Box -->
              <div style="background-color: #f3f4f6; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin: 20px 0;">
                <table style="width: 100%; border-collapse: collapse;">
                  <tr>
                    <td style="padding: 8px 0; font-size: 14px; font-weight: 600;">Global Schema Baseline:</td>
                    <td style="padding: 8px 0; font-size: 14px; text-align: right; color: #047857; font-weight: bold;">${readiness}/100 (Optimal Syntax)</td>
                  </tr>
                  <tr>
                    <td style="padding: 8px 0; font-size: 14px; font-weight: 600;">Target Location Grounding:</td>
                    <td style="padding: 8px 0; font-size: 14px; text-align: right; color: #b45309; font-weight: bold;">${proximity}% (Needs Attention)</td>
                  </tr>
                </table>
              </div>

              <h3 style="color: #111827; font-size: 16px; margin-top: 24px;">Priority Remediation Roadmap:</h3>
              <ol style="padding-left: 20px; font-size: 14px; color: #374151;">
                <li><strong>Anchor Regional Entity Schema:</strong> Inject nested <code>LocalBusiness</code> and <code>serviceArea</code> nodes linked to Wikidata.</li>
                <li><strong>Publish Location-Specific Evidence:</strong> Deploy case studies addressing targeted Australian customer queries.</li>
                <li><strong>Expand Passage Context Chunking:</strong> Structure high-density 150-character answer blocks under H2/H3 headings.</li>
              </ol>

              <!-- Commercial Call to Action -->
              <div style="margin: 32px 0; text-align: center;">
                <a href="https://aeobility.com.au/solutions/aeo-blueprint" style="background-color: #00cdd8; color: #000000; padding: 14px 28px; text-decoration: none; font-weight: bold; border-radius: 8px; display: inline-block; font-size: 14px;">
                  Implement with The AEObility Blueprint ($995 AUD) &rarr;
                </a>
                <p style="font-size: 12px; color: #6b7280; margin-top: 8px;">10-business-day fixed scope &bull; 100% credited to sprints &bull; Zero lock-in contracts</p>
              </div>

              <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 24px 0;" />
              <p style="font-size: 12px; color: #9ca3af; text-align: center;">
                AEObility &bull; Perth, Western Australia &bull; <a href="https://aeobility.com.au" style="color: #00cdd8;">aeobility.com.au</a>
              </p>
            </div>
          `,
        });

        return { ok: true };
      },

      async submitQuoteForm({
        name,
        email,
        businessName,
        website,
        service,
        message
      }: {
        name: string;
        email: string;
        businessName?: string;
        website?: string;
        service?: string;
        message?: string;
      }) {
        if (!name || !email) {
          throw new Error("Missing required fields");
        }

        const resend = new Resend(process.env.RESEND_API_KEY || "re_dummykeyforbuild");

        await resend.emails.send({
          from: "AEObility <noreply@aeobility.com.au>",
          to: "support@aeobility.com.au",
          subject: "New AEObility Quote Request",
          html: `
            <h2>New Quote Request</h2>
            <p><strong>Name:</strong> ${name}</p>
            <p><strong>Email:</strong> ${email}</p>
            <p><strong>Business Name:</strong> ${businessName || "Not provided"}</p>
            <p><strong>Website:</strong> ${website || "Not provided"}</p>
            <p><strong>Service Interest:</strong> ${service || "Not specified"}</p>
            <p><strong>Message/Notes:</strong> ${message || "None"}</p>
          `,
        });

        await resend.emails.send({
          from: "AEObility <noreply@aeobility.com.au>",
          to: email,
          subject: "Your AEObility Quote Request Has Been Received",
          html: `
            <p>Hi ${name},</p>
            <p>Thank you for requesting a quote from AEObility.</p>
            <p>Our team in Perth, Australia will review your details and prepare a tailored plan and pricing breakdown for your business within 24 business hours.</p>
          `,
        });

        return { ok: true };
      }
    };
  }
};
