/**
 * Utility to convert US English spelling to Australian English (AU) conventions.
 */
export function toAustralianEnglish(text: string): string {
  if (!text) return text;

  return text
    // -ize / -ization -> -ise / -isation
    .replace(/\bOptimization\b/g, 'Optimisation')
    .replace(/\boptimization\b/g, 'optimisation')
    .replace(/\bOptimizations\b/g, 'Optimisations')
    .replace(/\boptimizations\b/g, 'optimisations')
    .replace(/\bOptimize\b/g, 'Optimise')
    .replace(/\boptimize\b/g, 'optimise')
    .replace(/\bOptimized\b/g, 'Optimised')
    .replace(/\boptimized\b/g, 'optimised')
    .replace(/\bOptimizing\b/g, 'Optimising')
    .replace(/\boptimizing\b/g, 'optimising')
    .replace(/\bSynthesize\b/g, 'Synthesise')
    .replace(/\bsynthesize\b/g, 'synthesise')
    .replace(/\bSynthesized\b/g, 'Synthesised')
    .replace(/\bsynthesized\b/g, 'synthesised')
    .replace(/\bSynthesizing\b/g, 'Synthesising')
    .replace(/\bsynthesizing\b/g, 'synthesising')
    .replace(/\bSpecialized\b/g, 'Specialised')
    .replace(/\bspecialized\b/g, 'specialised')
    .replace(/\bSpecializing\b/g, 'Specialising')
    .replace(/\bspecializing\b/g, 'specialising')
    .replace(/\bSpecialize\b/g, 'Specialise')
    .replace(/\bspecialize\b/g, 'specialise')
    .replace(/\bAnalyze\b/g, 'Analyse')
    .replace(/\banalyze\b/g, 'analyse')
    .replace(/\bAnalyzed\b/g, 'Analysed')
    .replace(/\banalyzed\b/g, 'analysed')
    .replace(/\bAnalyzing\b/g, 'Analysing')
    .replace(/\banalyzing\b/g, 'analysing')
    .replace(/\bPrioritize\b/g, 'Prioritise')
    .replace(/\bprioritize\b/g, 'prioritise')
    .replace(/\bPrioritized\b/g, 'Prioritised')
    .replace(/\bprioritized\b/g, 'prioritised')
    .replace(/\bPrioritizing\b/g, 'Prioritising')
    .replace(/\bprioritizing\b/g, 'prioritising')
    .replace(/\bOrganize\b/g, 'Organise')
    .replace(/\borganize\b/g, 'organise')
    .replace(/\bOrganized\b/g, 'Organised')
    .replace(/\borganized\b/g, 'organised')
    .replace(/\bOrganizing\b/g, 'Organising')
    .replace(/\borganizing\b/g, 'organising')
    .replace(/\bOrganization\b/g, 'Organisation')
    .replace(/\borganization\b/g, 'organisation')
    .replace(/\bOrganizations\b/g, 'Organisations')
    .replace(/\borganizations\b/g, 'organisations')
    .replace(/\bCategorize\b/g, 'Categorise')
    .replace(/\bcategorize\b/g, 'categorise')
    .replace(/\bCategorized\b/g, 'Categorised')
    .replace(/\bcategorized\b/g, 'categorised')
    .replace(/\bCustomization\b/g, 'Customisation')
    .replace(/\bcustomization\b/g, 'customisation')
    .replace(/\bCustomize\b/g, 'Customise')
    .replace(/\bcustomize\b/g, 'customise')
    .replace(/\bCustomized\b/g, 'Customised')
    .replace(/\bcustomized\b/g, 'customised')
    .replace(/\bBehavior\b/g, 'Behaviour')
    .replace(/\bbehavior\b/g, 'behaviour')
    .replace(/\bBehaviors\b/g, 'Behaviours')
    .replace(/\bbehaviors\b/g, 'behaviours')
    .replace(/\bColor\b/g, 'Colour')
    .replace(/\bcolor\b/g, 'colour')
    .replace(/\bColors\b/g, 'Colours')
    .replace(/\bcolors\b/g, 'colours');
}
