import React, { Suspense } from 'react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import DiagnosticEngine from '@/components/DiagnosticEngine';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Run a Free AI Visibility Scan | AEObility",
  description: "Test your business details today. Run a free visibility scan to check your structured data, location signals and service information formatting.",
  alternates: {
    canonical: "https://aeobility.com.au/diagnostic",
  },
  keywords: [
    "free AI visibility scan",
    "AEO diagnostic tool",
    "structured data check Australia",
    "local signals audit",
    "AI search audit",
    "search visibility score",
    "service information formatting"
  ]
};

export default function DiagnosticPage() {
  const schema = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebPage",
        "@id": "https://aeobility.com.au/diagnostic#webpage",
        "url": "https://aeobility.com.au/diagnostic",
        "name": "Run a Free AI Visibility Scan | AEObility",
        "description": "Test your business details today. Run a free visibility scan to check your structured data, location signals and service information formatting.",
        "publisher": {
          "@type": "Organization",
          "name": "AEObility",
          "url": "https://aeobility.com.au"
        }
      },
      {
        "@type": "WebApplication",
        "@id": "https://aeobility.com.au/diagnostic#webapp",
        "name": "AI Visibility Diagnostic Engine",
        "url": "https://aeobility.com.au/diagnostic",
        "applicationCategory": "BusinessApplication",
        "operatingSystem": "All",
        "browserRequirements": "Requires JavaScript",
        "description": "Interactive visibility diagnostic tool evaluating structured data, location signals, and service information formatting across primary search platforms.",
        "about": [
          {
            "@type": "Thing",
            "@id": "https://aeobility.com.au/services/aeo#service",
            "name": "Answer Engine Optimisation"
          }
        ],
        "mentions": [
          {
            "@type": "Thing",
            "name": "Vector Proximity",
            "description": "Cosine similarity matching models across transformer embedding spaces."
          },
          {
            "@type": "Thing",
            "name": "Entity Salience",
            "description": "Algorithmic extraction weight of core brand nouns within knowledge graphs."
          },
          {
            "@type": "Thing",
            "name": "Chunking",
            "description": "Fragmenting unstructured textual blocks into precise semantic vector windows."
          },
          {
            "@type": "Thing",
            "name": "Embeddings",
            "description": "High-dimensional coordinate layouts generated by transformer-based neural nets."
          }
        ],
        "provider": {
          "@type": "Organization",
          "name": "AEObility",
          "url": "https://aeobility.com.au"
        }
      }
    ]
  };

  return (
    <div className="min-h-screen bg-black text-white flex flex-col font-sans selection:bg-aeo-cyan selection:text-black">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <Navbar />
      
      <main className="flex-1 w-full max-w-4xl mx-auto px-4 sm:px-6 pt-12 pb-28 sm:pb-20 flex flex-col items-center">
        <Suspense fallback={<div className="text-zinc-400 text-sm animate-pulse font-mono py-12">Initialising Free Visibility Scanner...</div>}>
          <DiagnosticEngine />
        </Suspense>
      </main>

      <Footer />
    </div>
  );
}
