import React, { Suspense } from 'react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import DiagnosticEngine from '@/components/DiagnosticEngine';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Run a Free AI Visibility Scan | AEObility",
  description: "Test your business details today. Run a free visibility scan to check your structured data, location signals and service information formatting.",
  alternates: {
    canonical: "https://aeobility.com.au/diagnostic",
  },
  keywords: [
    "free AI visibility scan",
    "AEO diagnostic tool",
    "structured data check Australia",
    "local signals audit",
    "AI search audit",
    "search visibility score",
    "service information formatting"
  ]
};

export default function DiagnosticPage() {
  const schema = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebPage",
        "@id": "https://aeobility.com.au/diagnostic#webpage",
        "url": "https://aeobility.com.au/diagnostic",
        "name": "Run a Free AI Visibility Scan | AEObility",
        "description": "Test your business details today. Run a free visibility scan to check your structured data, location signals and service information formatting.",
        "publisher": {
          "@type": "Organization",
          "name": "AEObility",
          "url": "https://aeobility.com.au"
        }
      },
      {
        "@type": "WebApplication",
        "@id": "https://aeobility.com.au/diagnostic#webapp",
        "name": "AI Visibility Diagnostic Engine",
        "url": "https://aeobility.com.au/diagnostic",
        "applicationCategory": "BusinessApplication",
        "operatingSystem": "All",
        "browserRequirements": "Requires JavaScript",
        "description": "Interactive visibility diagnostic tool evaluating structured data, location signals, and service information formatting across primary search platforms.",
        "about": [
          {
            "@type": "Thing",
            "@id": "https://aeobility.com.au/services/aeo#service",
            "name": "Answer Engine Optimisation"
          }
        ],
        "mentions": [
          {
            "@type": "Thing",
            "name": "Vector Proximity",
            "description": "Cosine similarity matching models across transformer embedding spaces."
          },
          {
            "@type": "Thing",
            "name": "Entity Salience",
            "description": "Algorithmic extraction weight of core brand nouns within knowledge graphs."
          },
          {
            "@type": "Thing",
            "name": "Chunking",
            "description": "Fragmenting unstructured textual blocks into precise semantic vector windows."
          },
          {
            "@type": "Thing",
            "name": "Embeddings",
            "description": "High-dimensional coordinate layouts generated by transformer-based neural nets."
          }
        ],
        "provider": {
          "@type": "Organization",
          "name": "AEObility",
          "url": "https://aeobility.com.au"
        }
      },
      {
        "@type": "FAQPage",
        "@id": "https://aeobility.com.au/diagnostic#faq",
        "mainEntity": [
          {
            "@type": "Question",
            "name": "How is AI Search (AEO) different from regular SEO?",
            "acceptedAnswer": {
              "@type": "Answer",
              "text": "Traditional SEO optimises for keywords, blue links, and search rankings. Answer Engine Optimisation (AEO) structures your content, schema, and entity relationships so generative AI engines (like ChatGPT, Perplexity, and Gemini) extract and cite your business as the definitive answer."
            }
          },
          {
            "@type": "Question",
            "name": "Will this scan affect my live website speed or uptime?",
            "acceptedAnswer": {
              "@type": "Answer",
              "text": "No. The diagnostic scan is a safe, lightweight, read-only external query. It inspects public HTML, schema markup, and vector distance without impacting server load or uptime."
            }
          },
          {
            "@type": "Question",
            "name": "What happens after I run the scan?",
            "acceptedAnswer": {
              "@type": "Answer",
              "text": "You receive an instant on-screen diagnostic report showing your 0–100 AI Readiness Score, simulated AI impression, and factual grounding breakdown. You can also chat directly with AI Bill to explore specific remediation steps."
            }
          },
          {
            "@type": "Question",
            "name": "Do I need technical skills to understand the report?",
            "acceptedAnswer": {
              "@type": "Answer",
              "text": "No. Every diagnostic evaluation provides plain-English summaries alongside technical specifics, categorising findings into quick wins and structural improvements."
            }
          },
          {
            "@type": "Question",
            "name": "Do I need to jump on a sales call to get my report?",
            "acceptedAnswer": {
              "@type": "Answer",
              "text": "No. Your report generates directly on-screen with zero sales pressure, zero lock-in contracts, and transparent fixed-price remediation options."
            }
          }
        ]
      }
    ]
  };

  return (
    <div className="min-h-screen bg-[#080B11] text-white flex flex-col font-sans selection:bg-aeo-cyan selection:text-black relative overflow-x-clip">
      {/* 1. Under-Layer Lighting Mesh (The Refraction Engine) */}
      <div className="fixed inset-0 pointer-events-none z-0 overflow-hidden">
        {/* Top-Right Ambient Violet/Indigo Bloom */}
        <div 
          className="absolute -top-32 -right-32 w-[650px] h-[650px] rounded-full blur-[120px] opacity-80"
          style={{
            background: 'radial-gradient(circle, rgba(99, 102, 241, 0.14) 0%, rgba(99, 102, 241, 0.04) 45%, transparent 70%)'
          }}
        />
        {/* Mid-Left Electric Cyan Bloom */}
        <div 
          className="absolute top-[32%] -left-48 w-[720px] h-[720px] rounded-full blur-[140px] opacity-75"
          style={{
            background: 'radial-gradient(circle, rgba(0, 229, 255, 0.09) 0%, rgba(0, 205, 216, 0.03) 40%, transparent 65%)'
          }}
        />
        {/* Bottom-Right Magenta Accent Pool */}
        <div 
          className="absolute bottom-10 -right-24 w-[550px] h-[550px] rounded-full blur-[130px] opacity-60"
          style={{
            background: 'radial-gradient(circle, rgba(236, 72, 153, 0.07) 0%, rgba(139, 92, 246, 0.03) 45%, transparent 70%)'
          }}
        />
      </div>

      {/* 2. Tactile SVG Noise Grain Overlay */}
      <div 
        className="fixed inset-0 pointer-events-none z-[1] opacity-[0.025] mix-blend-overlay"
        style={{
          backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.8' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E")`
        }}
      />

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <div className="relative z-10 flex flex-col min-h-screen">
        <Navbar />
        
        <main className="flex-1 w-full max-w-4xl mx-auto px-4 sm:px-6 pt-6 sm:pt-10 pb-32 sm:pb-24 flex flex-col items-center">
          <Suspense fallback={<div className="text-zinc-400 text-sm animate-pulse font-mono py-12">Initialising Free Visibility Scanner...</div>}>
            <DiagnosticEngine />
          </Suspense>
        </main>

        <Footer />
      </div>
    </div>
  );
}
